version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 22
    # registries:
    #   - jfrog-artifactory
    #   - jfrog-artifactory-2

# registries:
#   jfrog-artifactory:
#     type: "npm-registry"
#     url: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/dpndbt-pvt-repo-npm-key/"
#     token: "${{secrets.JFROG_ARTIFACTORY_TOKEN}}"
#     scope: "@mycompany"
#     # replaces-base: true

#   jfrog-artifactory-2:
#     type: "npm-registry"
#     url: "https://jfrogghdemo.jfrog.io/artifactory/api/npm/dpndbt-pvt-repo-npm-key/"
#     token: "${{secrets.JFROG_ARTIFACTORY_TOKEN}}"
#     scope: "@abhishekbhaskar"
#     # replaces-base: true
